version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    tty: true
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client:/usr/share/nginx/html
